### ISSUE TITLE
Sabaki: increase estimate text size

### ISSUE THREAD

**Issue by Terkwood** [Terkwood/BUGOUT#160]
Estimate bar should have text size comparable to scoring bar.  

See index.css:

```css
    #scoring {
        font-size: 1.6em;
    }
    #scoring button {
        font-size: 1.2em;
    }
```
